### ISSUE TITLE
Continuous view includes data outside of the TTL period

### ISSUE THREAD

**Issue by andrew-blake** [pipelinedb/pipelinedb#1930] opened 2018-06-07 17:25 UTC
After bootstrapping historic data into a stream in a single transaction, the a continuous view includes data outside of the TTL period. 

Subsequent inserts into the stream causes the CV to refresh and honour the TTL period.

I believe the CV should always apply the TTL period filter rather than waiting for rows to be deleted by subsequent inserts.

**Create CV with 5 min TTL**
```
create foreign table source_stream
(
	id serial,
	timestamp_tz timestamp with time zone,
	sid text
) server pipelinedb;

create view stats_cv_5m_ttl with ( action = materialize, ttl = '5 minutes', ttl_column = 'timestamp_1m') as
    select
          minute(timestamp_tz) as timestamp_1m
        , count(*) as cnt_1m
        , count(distinct sid) as cnt_unique_sids_1m
        , exact_count_distinct (sid) as cnt_unique_sids_1m_exact
    from source_stream
    group by 1
;
```

**Insert historic data in single transaction**
```
begin transaction;
insert into source_stream (id, timestamp_tz, sid) values (1, now() - '9 minutes'::interval, 'aaabbccdd11');
insert into source_stream (id, timestamp_tz, sid) values (2, now() - '8 minutes'::interval, 'aaabbccdd22');
insert into source_stream (id, timestamp_tz, sid) values (3, now() - '7 minutes'::interval, 'aaabbccdd33');
insert into source_stream (id, timestamp_tz, sid) values (4, now() - '6 minutes'::interval, 'aaabbccdd33');
insert into source_stream (id, timestamp_tz, sid) values (5, now() - '5 minutes'::interval, 'aaabbccdd33');
insert into source_stream (id, timestamp_tz, sid) values (6, now() - '4 minutes'::interval, 'aaabbccdd11');
insert into source_stream (id, timestamp_tz, sid) values (7, now() - '3 minutes'::interval, 'aaabbccdd22');
insert into source_stream (id, timestamp_tz, sid) values (8, now() - '2 minutes'::interval, 'aaabbccdd33');
insert into source_stream (id, timestamp_tz, sid) values (9, now() - '1 minutes'::interval, 'aaabbccdd33');
insert into source_stream (id, timestamp_tz, sid) values (10, now() - '0 minutes'::interval, 'aaabbccdd33');
commit;
```

**CV shows data beyond the TTL**
```
select
    timestamp_1m
    , cnt_1m
    , cnt_unique_sids_1m
    , cnt_unique_sids_1m_exact
from stats_cv_5m_ttl
order by timestamp_1m;


      timestamp_1m      | cnt_1m | cnt_unique_sids_1m | cnt_unique_sids_1m_exact
------------------------+--------+--------------------+--------------------------
 2018-06-07 17:14:00+00 |      1 |                  1 |                        1
 2018-06-07 17:15:00+00 |      1 |                  1 |                        1
 2018-06-07 17:16:00+00 |      1 |                  1 |                        1
 2018-06-07 17:17:00+00 |      1 |                  1 |                        1
 2018-06-07 17:18:00+00 |      1 |                  1 |                        1
 2018-06-07 17:19:00+00 |      1 |                  1 |                        1
 2018-06-07 17:20:00+00 |      1 |                  1 |                        1
 2018-06-07 17:21:00+00 |      1 |                  1 |                        1
 2018-06-07 17:22:00+00 |      1 |                  1 |                        1
 2018-06-07 17:23:00+00 |      1 |                  1 |                        1
(10 rows)
```

**Insert a new row, causing the CV to refresh and only show data within TTL**
```
insert into source_stream (id, timestamp_tz, sid) values (11, now() - '0 minutes'::interval, 'aaabbccdd44');
```

```
select
    timestamp_1m
    , cnt_1m
    , cnt_unique_sids_1m
    , cnt_unique_sids_1m_exact
from stats_cv_5m_ttl
order by timestamp_1m;

      timestamp_1m      | cnt_1m | cnt_unique_sids_1m | cnt_unique_sids_1m_exact
------------------------+--------+--------------------+--------------------------
 2018-06-07 17:20:00+00 |      1 |                  1 |                        1
 2018-06-07 17:21:00+00 |      1 |                  1 |                        1
 2018-06-07 17:22:00+00 |      1 |                  1 |                        1
 2018-06-07 17:23:00+00 |      1 |                  1 |                        1
 2018-06-07 17:24:00+00 |      1 |                  1 |                        1
(5 rows)
```

**Comment by derekjn** [comment] 2018-06-07 17:41
Hi @andrew-blake! This is actually [expected behavior](http://docs.pipelinedb.com/continuous-views.html#time-to-live-ttl-expiration). The TTL is merely a hint to the `reaper` process as to when the rows can be deleted, it is not a hard limit.

However, [sliding window](http://docs.pipelinedb.com/sliding-windows.html) CVs do filter out out-of-window data at read time, so that may be what you want here.

Another option is to simply create a `VIEW` over your CV that filters out the out-of-window rows:

```sql

CREATE CONTINUOUS VIEW v WITH (ttl='1 hour', ttl_column='second') AS
  SELECT second(ts), count(*) FROM s
GROUP BY second;

CREATE VIEW filter AS SELECT * FROM v
  WHERE second > now() - interval '1 hour');
```

Most use cases for TTLs are just to ensure rows are eventually cleaned up and not necessarily to provide a hard limit, so we've consciously decided not to implicitly introduce a read-time filter since you can pretty easily get that with a `VIEW` anyways.

Please let us know if you have any questions about anything!

**Comment by andrew-blake** [comment] 2018-06-07 17:53
Thanks for letting me know.

I tried using sliding windows, but also obtained data outside the sliding window period, hence why I tried using TTLs instead.

```
create foreign table source_stream
(
	id serial,
	timestamp_tz timestamp with time zone,
	sid text
) server pipelinedb;

create view stats_cv_5m_sw with ( action = materialize, sw = '5 minutes', step_factor=1) as
    select
          minute(timestamp_tz) as timestamp_1m
        , count(*) as cnt_1m
        , count(distinct sid) as cnt_unique_sids_1m
        , exact_count_distinct (sid) as cnt_unique_sids_1m_exact
    from source_stream
    group by 1
;

begin transaction;
insert into source_stream (id, timestamp_tz, sid) values (1, now() - '9 minutes'::interval, 'aaabbccdd11');
insert into source_stream (id, timestamp_tz, sid) values (2, now() - '8 minutes'::interval, 'aaabbccdd22');
insert into source_stream (id, timestamp_tz, sid) values (3, now() - '7 minutes'::interval, 'aaabbccdd33');
insert into source_stream (id, timestamp_tz, sid) values (4, now() - '6 minutes'::interval, 'aaabbccdd33');
insert into source_stream (id, timestamp_tz, sid) values (5, now() - '5 minutes'::interval, 'aaabbccdd33');
insert into source_stream (id, timestamp_tz, sid) values (6, now() - '4 minutes'::interval, 'aaabbccdd11');
insert into source_stream (id, timestamp_tz, sid) values (7, now() - '3 minutes'::interval, 'aaabbccdd22');
insert into source_stream (id, timestamp_tz, sid) values (8, now() - '2 minutes'::interval, 'aaabbccdd33');
insert into source_stream (id, timestamp_tz, sid) values (9, now() - '1 minutes'::interval, 'aaabbccdd33');
insert into source_stream (id, timestamp_tz, sid) values (10, now() - '0 minutes'::interval, 'aaabbccdd33');
commit;


select
    timestamp_1m
    , cnt_1m
    , cnt_unique_sids_1m
    , cnt_unique_sids_1m_exact
from stats_cv_5m_sw
order by timestamp_1m;

      timestamp_1m      | cnt_1m | cnt_unique_sids_1m | cnt_unique_sids_1m_exact
------------------------+--------+--------------------+--------------------------
 2018-06-07 17:43:00+00 |      1 |                  1 |                        1
 2018-06-07 17:44:00+00 |      1 |                  1 |                        1
 2018-06-07 17:45:00+00 |      1 |                  1 |                        1
 2018-06-07 17:46:00+00 |      1 |                  1 |                        1
 2018-06-07 17:47:00+00 |      1 |                  1 |                        1
 2018-06-07 17:48:00+00 |      1 |                  1 |                        1
 2018-06-07 17:49:00+00 |      1 |                  1 |                        1
 2018-06-07 17:50:00+00 |      1 |                  1 |                        1
 2018-06-07 17:51:00+00 |      1 |                  1 |                        1
 2018-06-07 17:52:00+00 |      1 |                  1 |                        1
(10 rows)
```

Am I doing something wrong ? Are those WITH options correct ?

**Comment by derekjn** [comment] 2018-06-07 18:06
@andrew-blake can you share the output of this?

```
\d+ stats_cv_5m_sw
```

**Comment by andrew-blake** [comment] 2018-06-07 18:27
```
pipeline=# \d+ stats_cv_5m_sw
                                         View "public.stats_cv_5m_sw"
          Column          |           Type           | Collation | Nullable | Default | Storage | Description
--------------------------+--------------------------+-----------+----------+---------+---------+-------------
 timestamp_1m             | timestamp with time zone |           |          |         | plain   |
 cnt_1m                   | bigint                   |           |          |         | plain   |
 cnt_unique_sids_1m       | bigint                   |           |          |         | plain   |
 cnt_unique_sids_1m_exact | integer                  |           |          |         | plain   |
View definition:
 SELECT minute(timestamp_tz) AS timestamp_1m,
    count(*) AS cnt_1m,
    count(DISTINCT sid) AS cnt_unique_sids_1m,
    exact_count_distinct(sid) AS cnt_unique_sids_1m_exact
   FROM source_stream
  WHERE arrival_timestamp > (clock_timestamp() - '00:05:00'::interval)
  GROUP BY (minute(timestamp_tz));
Options: action=materialize, viewrelid=19302, viewtype=19304, viewatype=19303, matrelid=19293, matreltype=19295, matrelatype=19294, matreltoastrelid=19296, matreltoasttype=19297, matreltoastindid=19298, seqrelid=19299, seqreltype=19300, osrelid=19306, osreltype=19308, osrelatype=19307, pkindid=19311, lookupindid=19310, ttl=300, ttl_column=arrival_timestamp
```

```
pipeline=# select clock_timestamp();
        clock_timestamp
-------------------------------
 2018-06-07 18:27:00.857314+00
(1 row)
```

**Comment by andrew-blake** [comment] 2018-06-07 18:28
Btw, the view is now empty

**Comment by derekjn** [comment] 2018-06-07 18:32
@andrew-blake so if you're going to use a column other than `arrival_timestamp` for your SW, you need to construct the window clause explicitly by referencing it in the `WHERE` clause of the CV definition, like so:

```sql
CREATE CONTINUOUS VIEW stats_cv_5m_sw AS
 SELECT minute(timestamp_tz) AS timestamp_1m,
    count(*) AS cnt_1m,
    count(DISTINCT sid) AS cnt_unique_sids_1m,
    exact_count_distinct(sid) AS cnt_unique_sids_1m_exact
   FROM source_stream
  WHERE timestamp_tz > (clock_timestamp() - '00:05:00'::interval)
  GROUP BY (minute(timestamp_tz));
```

What's happening with your current CV is that `sw=` implicitly uses `arrival_timestamp`.

**Comment by andrew-blake** [comment] 2018-06-07 18:53
Thanks for clarifying.  

As backfilling data will always require using a non-insertion time where clause, can I suggest you add a ‘sw_column’ WITH option to change the default?

Btw, really excited by this project. Can’t wait until 1.0.0 as I’m hoping to use this in conjunction with TimescaleDB and my multi TB timeseries database! Is there an updated ETA for that?

**Comment by derekjn** [comment] 2018-06-07 20:18
> As backfilling data will always require using a non-insertion time where clause, can I suggest you add a ‘sw_column’ WITH option to change the default?

We definitely agree with you here! It's actually been an open issue for a while:

https://github.com/pipelinedb/pipelinedb/issues/1497

I've went ahead and added that issue to the `1.0.0` release as it's a fairly straightforward addition. In terms of timeline, we're getting pretty close (the extension code is currently in temporary private repo before merging it with this one) and we're aiming for the end of the month. That's a somewhat aggressive timeline but even if we need more time it won't be much more :)

**Comment by derekjn** [comment] 2018-06-08 03:35
@andrew-blake unless you have any further questions on this we can probably close this issue out and track the remaining work on https://github.com/pipelinedb/pipelinedb/issues/1497. In any case, we're happy to answer any more questions or take any feedback!

**Closed** 2018-06-08 07:10 UTC
