### ISSUE TITLE
High-fanout TRANSFORM stall

### ISSUE THREAD

**Issue by EliSnow** [pipelinedb/pipelinedb#1714] opened 2016-12-01 00:35 UTC
With the following I can consistently crash Pipeline:

```sql
DROP STREAM IF EXISTS s CASCADE;
CREATE STREAM s (json jsonb);

CREATE CONTINUOUS TRANSFORM t AS
  SELECT json, interval, resource
  FROM s
    CROSS JOIN generate_series(1, 4) AS x (interval)
    CROSS JOIN jsonb_array_elements(json->'foo') AS y (resource);

CREATE CONTINUOUS VIEW v AS
  SELECT 1 FROM output_of('t');

-- generate some json and insert it into the stream
-- INSERT INTO s (json) SELECT json
--   FROM generate_series(1, 100) AS row_count
--     CROSS JOIN LATERAL (
--       SELECT row_count, jsonb_build_object('foo', jsonb_agg(el)) AS json
--       FROM generate_series(1, 100) AS n
--        CROSS JOIN LATERAL (
--         SELECT n, jsonb_object_agg(key, value) AS el
--         FROM generate_series(1, 3) AS y
--         CROSS JOIN LATERAL (
--           SELECT md5((random() + y)::text) AS key, string_agg(md5(random()::text), '') AS value
--           FROM generate_series(1, 400) AS n
--         ) x
--       ) x
--     ) x;

COPY (SELECT json
  FROM generate_series(1, 100) AS row_count
    CROSS JOIN LATERAL (
      SELECT row_count, jsonb_build_object('foo', jsonb_agg(el)) AS json
      FROM generate_series(1, 100) AS n
       CROSS JOIN LATERAL (
        SELECT n, jsonb_object_agg(key, value) AS el
        FROM generate_series(1, 3) AS y
        CROSS JOIN LATERAL (
          SELECT md5((random() + y)::text) AS key, string_agg(md5(random()::text), '') AS value
          FROM generate_series(1, 400) AS n
        ) x
      ) x
    ) x) TO '/home/pipeline/json';

COPY s (json) FROM '/home/pipeline/json';
```

Note that the commented out `INSERT` will also crash the database.

The following which is the equivalent of the above CV without the `TRANSFORM` does not crash:

```sql
DROP STREAM IF EXISTS s CASCADE;
CREATE STREAM s (json jsonb);

CREATE CONTINUOUS VIEW v AS
  SELECT 1
  FROM s
    CROSS JOIN generate_series(1, 4) AS x (interval)
    CROSS JOIN jsonb_array_elements(json->'foo') AS y (resource);

-- generate some json and insert it into the stream
-- INSERT INTO s (json) SELECT json
--   FROM generate_series(1, 100) AS row_count
--     CROSS JOIN LATERAL (
--       SELECT row_count, jsonb_build_object('foo', jsonb_agg(el)) AS json
--       FROM generate_series(1, 100) AS n
--        CROSS JOIN LATERAL (
--         SELECT n, jsonb_object_agg(key, value) AS el
--         FROM generate_series(1, 3) AS y
--         CROSS JOIN LATERAL (
--           SELECT md5((random() + y)::text) AS key, string_agg(md5(random()::text), '') AS value
--           FROM generate_series(1, 400) AS n
--         ) x
--       ) x
--     ) x;
    
COPY (SELECT json
  FROM generate_series(1, 100) AS row_count
    CROSS JOIN LATERAL (
      SELECT row_count, jsonb_build_object('foo', jsonb_agg(el)) AS json
      FROM generate_series(1, 100) AS n
       CROSS JOIN LATERAL (
        SELECT n, jsonb_object_agg(key, value) AS el
        FROM generate_series(1, 3) AS y
        CROSS JOIN LATERAL (
          SELECT md5((random() + y)::text) AS key, string_agg(md5(random()::text), '') AS value
          FROM generate_series(1, 400) AS n
        ) x
      ) x
    ) x) TO '/home/pipeline/json';

COPY s (json) FROM '/home/pipeline/json';
```

There seems to be a second bug, where in the second code snippet if you use the `INSERT` it causes a deadlock. I can create a second issue for that if you like.

If it makes any difference to repro, I am running in a docker container with 8 combiners and 8 workers, 768MB of shmem. Let me know if you need any other details.

**Comment by usmanm** [comment] 2016-12-01 03:35
Is there anything in the server log related to the crash?

**Comment by EliSnow** [comment] 2016-12-01 04:11
Nothing very helpful (from what I can tell):
```
LOG:  worker process: worker2 [stats] (PID 7448) was terminated by signal 9: Killed
DETAIL:  Failed process was running: worker2 [stats]
LOG:  terminating any other active server processes
WARNING:  terminating connection because of crash of another server process
DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
HINT:  In a moment you should be able to reconnect to the database and repeat your command.
WARNING:  terminating connection because of crash of another server process
DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
HINT:  In a moment you should be able to reconnect to the database and repeat your command.
WARNING:  terminating connection because of crash of another server process
DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
HINT:  In a moment you should be able to reconnect to the database and repeat your command.
FATAL:  the database system is in recovery mode
LOG:  all server processes terminated; reinitializing
```

Is there a setting I can enable to get more verbose error messages?

**Comment by derekjn** [comment] 2016-12-01 04:50
It looks like an OOM, are you seeing rising memory usage leading up to the proc being killed?

**Comment by EliSnow** [comment] 2016-12-01 04:55
That sounds right because I'll occasionally see `pzmq failed to send msg: Cannot allocate memory` in the logs as well. I will verify tomorrow.

**Comment by EliSnow** [comment] 2016-12-01 16:21
There was definitely a huge rise in memory usage during the insertion of the data. The db was sitting at about 140MB when idle then shot up to 7.5GB during the final copy. You can see it drop off when the sig kill came from the kernel.

![memory](https://cloud.githubusercontent.com/assets/714089/20801821/55b9b3b4-b7a7-11e6-99e6-04b99bd08265.png)

**Comment by EliSnow** [comment] 2016-12-01 16:48
The second query without the `TRANSFORM` maxes out at about 635MB of ram usage and stays steady, which I'm guessing is PostgreSQL keeping all of the data in it's caches.

**Comment by usmanm** [comment] 2016-12-01 18:31
Ok, that helps us narrow down the problem to a memory leak. Thanks for reporting @EliSnow, will dig into this today and report back!

**Comment by EliSnow** [comment] 2016-12-01 19:25
Thanks, @usmanm and @derekjn. Let me know if I can provide any more details.

**Comment by derekjn** [comment] 2016-12-02 18:38
> If it makes any difference to repro, I am running in a docker container with 8 combiners and 8 workers, 768MB of shmem.

@EliSnow I looked into this and that JSON file you're generating is `368 MB`, so your rows here are `3.68 MB` each. With huge rows and that many workers and combiners on a system with less than `1 GB` of memory, I would fully expect out-of-memory errors like this. 

`continuous_query_combiner_work_mem` specifies the memory that each combiner will try to allocate (defaults to `256 MB`), so you can try reducing that to work for this scenario although it's not clear if you actually need this to work or if you're just experimenting. Either way, this is fully expected behavior.

**Comment by EliSnow** [comment] 2016-12-02 18:45
@derekjn, the (test) machine itself has 8gb of memory. Are you saying it is necessary to have 256 * 16 (8 workers + 8 combiners) in shared memory? 
Why is this a problem with a `TRANSFORM` but without it everything is fine?
Also, before you close this issue, there is still the bug of the deadlock. I have been able to workaround the `TRANSFORM` crash, but I am blocked by this deadlock bug.

**Comment by derekjn** [comment] 2016-12-02 18:51
I actually misread that it was shmem (and not regular memory), so with `8GB` you may be fine, let me take another look here...

**Comment by EliSnow** [comment] 2016-12-02 19:04
Thanks, @derekjn. My guess is the `TRANSFORM` crash happens because the output is so much greater than the input and it is executing faster than the `CONTINUOUS VIEW` can ingest. I have been able to work around it by creating my own trigger procedure which loops over the result of the `jsonb_array_elements` and inserts them in one by one, but then it gets stuck with the deadlock bug.

**Comment by derekjn** [comment] 2016-12-12 20:20
With assertions enabled, even the CV (with the `CROSS JOINs`) causes an assertion failure here:

```
calc_non_nestloop_required_outer() at pathnode.c:1,536 0x773b77	
add_paths_to_joinrel() at joinpath.c:186 0x739c43	
make_join_rel() at joinrels.c:757 0x73cad5	
make_rels_by_clause_joins() at joinrels.c:274 0x73c060	
join_search_one_level() at joinrels.c:96 0x73bd0b	
standard_join_search() at allpaths.c:1,819 0x7279a4	
make_rel_from_joinlist() at allpaths.c:1,750 0x72791d	
make_one_rel() at allpaths.c:170 0x725594	
query_planner() at planmain.c:234 0x74e23a	
grouping_planner() at planner.c:1,547 0x750c13	
subquery_planner() at planner.c:624 0x74f120	
standard_planner() at planner.c:233 0x74e504	
planner() at planner.c:157 0x74e346	
```

With assertions disabled the result will most likely be an incorrect plan, which I'm guessing is the root cause here.

**Comment by derekjn** [comment] 2016-12-12 21:36
For reference, here are a couple of shrunken rows generated by the above sorcery:

```
{"foo": [{"95107bc6f225ae3a49bb7d27aa5bf139": "86dced0cfab434bab5261567516803480680a97bbad1acc159b7aa636dc516ab", "d212f9ef841a99c8206c2b0c4ee83211": "c96acca47d472ae84b8c482408d2c8ff20231d5ae76996ddc82a60ed441b2b20"}, {"3de9e313db7c5604890e45ca8399c346": "370ab951ba0005fbd7c5747fbdde08472c31c2872c4971dd4d9ac915edd86fb5", "8bd92103eff7caf5b7c22182db191887": "327ef2c4bacaae78a22609ec1e75500b57f197243a016cacbe11725f0cec8dc5"}]}
{"foo": [{"67fdcf08a17051fe130e9418d5d58e2f": "4c3dc629b932cc5a0995bd2979e83ba9c2207fa4118bde559d2e96cd1ba043d5", "f76dd275abdfff0053a36dcbdb338486": "2d5ea2e84150f187351ae5685503a04cdd8c42476aa1bafaef26d306f48f149f"}, {"73afbfdb4dd71b87fbab21875a5208e7": "ddb95d7fd7173ca1951bc9e26cd106cf09a56867cb452e9bc90ae2d2981f34d0", "85ff1434a38510f3a0a5e2168450b954": "c92a7a34fd0ef9ad43a4d6c60d3dc5e9f55fdd0d83b331cba081d9a18dbc39b4"}]}
```

The real rows just have much longer strings everywhere, with each event being about `3MB`.

**Comment by derekjn** [comment] 2016-12-12 23:01
I've got the planner fixed, now working on the cause of the stall. Fortunately this is extremely easy to repro with a single `INSERT` so we should have the fix soon. What seems to be happening is that the event isn't getting acked, so the writer process keeps waiting. The stall does not happen when `stream_insert_level` is `async`.

It most likely has something to do with such large events, as it also doesn't happen with the shrunken version of the events.

**Comment by usmanm** [comment] 2016-12-12 23:49
Maybe ZMQ is silently dropping the messages?

**Comment by derekjn** [comment] 2016-12-12 23:56
I'm thinking it's something along those lines, although there shouldn't be any limits on message size. Do any ZMQ settings come to mind?

**Comment by derekjn** [comment] 2016-12-13 00:09
One other thing of note is that the original events have a pretty high fanout of 400, so each event yields 400 events into the output stream. But because they still work with `async` inserts that may be irrelevant here.

**Comment by derekjn** [comment] 2016-12-13 03:48
The weird thing though is that, as @EliSnow pointed out and I've confirmed, there's no problem when using just a continuous view: input stream -> CV. The stall only happens when using a input stream -> transform -> output stream -> CV.

**Comment by usmanm** [comment] 2016-12-13 03:52
High fan out is the likely cause here. How many workers are you running with? The stall could be because the worker is writing to itself and reaches the HWM on the send buffer. CV output streams are inserted by combiners so we won't see a stall there.

**Comment by derekjn** [comment] 2016-12-13 03:59
I was running with a single worker, for which one event would cause the stall. I just tried with 2 workers and it did not stall. But @EliSnow mentioned using 8 workers, which I suppose would just delay the stall, right?

**Comment by usmanm** [comment] 2016-12-13 04:16
It will basically stall whenever a worker writes to its own socket and the HWM mark for the send buffer is hit. But this can happen with multiple workers as well if they are blocked on each others socket because the HWM is hit.

**Comment by usmanm** [comment] 2016-12-13 04:18
I think this is basically a recurrence of https://github.com/pipelinedb/pipelinedb/issues/1575.

**Comment by derekjn** [comment] 2016-12-13 20:45
It actually doesn't seem like this is a fanout issue. The following works fine:

```sql
CREATE STREAM s (x integer);
CREATE CONTINUOUS TRANSFORM t AS SELECT generate_series(1, 1000) FROM s;
CREATE CONTINUOUS VIEW v AS SELECT 1 FROM output_of('t');

INSERT INTO s (x) SELECT generate_series(1, 1000);
```

**Comment by derekjn** [comment] 2016-12-13 20:50
Scratch the last comment, it can actually be reproduced with the above.

**Comment by derekjn** [comment] 2016-12-13 20:51
Stalled here:

```
microbatch_send() at microbatch.c:540 0x77f5b1	
microbatch_send_to_worker() at microbatch.c:593 0x77f6f6	
ExecStreamInsert() at stream_fdw.c:593 0x79d476	
insert_into_rel() at transformReceiver.c:205 0x79e96f	
pipeline_stream_insert_batch() at transformReceiver.c:242 0x79eb56	
TransformDestReceiverFlush() at transformReceiver.c:271 0x79ec69	
flush_tuples() at cont_worker.c:176 0x794da2	
ContinuousQueryWorkerMain() at cont_worker.c:350 0x7953c9	
```

**Comment by usmanm** [comment] 2016-12-13 20:52
This is probably happening because the send HWM is hit.

**Comment by derekjn** [comment] 2016-12-13 22:33
@EliSnow so the fundamental problem here is that the transform has a very high fanout (given the sample input): for each event that it reads from `s`, it writes 400 rows into `output_of('t')`. Transforms producing many more rows than they consume is kind of an anti-pattern and as a result isn't handled particularly well at this point.

Ultimately workers can become stalled in this scenario because they write to the same place they read from, and are blocked when there's not enough room to write. They're unblocked when other workers read their output, but when the output size is much greater than the input, a stall can occurs. This ends up being a fundamentally complex problem. The stall only happens with transforms because transforms both read from and write to streams.

I'm not sure if the test data provided is representative of an actual dataset, but if your actual workload has a much lower fanout than 400:1 then there likely won't be any problems.

That being said, we still want to handle this scenario as intelligently we can. Here's a rough sketch on how we're going to improve things here:

* If a worker is producing too much output, it will begin spilling rows to disk
* The worker will then continue reading input rows to make room for its output
* The worker will make a best effort to write the spilled output rows as soon as possible

/cc @usmanm

**Comment by EliSnow** [comment] 2016-12-13 22:57
This scenario (sorcery 😉) is an exaggeration of my use case in terms of the actual size of the payload, but some of my data can easily have a fanout of 300:1, and it experiences the deadlock.

I appreciate you spending so much time on this. Is it possible the results of the transform could be generated like a cursor (or a generator in python) so the results are produced incrementally when the sink is ready to consume?

**Comment by derekjn** [comment] 2016-12-14 01:51
> I appreciate you spending so much time on this.

Of course! It's just a matter of implementation now, so not much longer until it's no longer an issue.

> Is it possible the results of the transform could be generated like a cursor (or a generator in python) so the results are produced incrementally when the sink is ready to consume?

The problem is that the worker process produces results *and* is the sink. This is why the issue only occurs for transforms: they take their input from streams and write the results out to the same stream infrastructure they read from, whereas combiners take their input directly from workers (there's no combiner <-> worker stream).

Using multiple worker processes lowers the probability of a high-fanout stall, but it turns out to be fairly complex to prevent without some kind of detection and handling as sketched out above.

**Comment by derekjn** [comment] 2016-12-16 00:10
@EliSnow this is fixed in `master` as soon as the PR lands. Fanouts will no longer stall the system, with the tradeoff being that you risk OOM if your fanned-out rows are too large. This will happen with the massive sample rows created by the above, but shouldn't be a concern with a realistic workload.

Two legitimate bugs were fixed because of this report, so thank you so much for bringing it to our attention, and thanks for your patience!

**Closed by derekjn** 2016-12-16 00:10 UTC
Labels: bug, deadlock

**Comment by EliSnow** [comment] 2016-12-16 19:25
@derekjn, thanks for all your work on these issues! I won't be able to test them out for possibly a few weeks. Hopefully my actual workload doesn't trigger an OOM.

In the event that it did, would a reasonable workaround be to move the `CROSS JOIN` out of the `TRANSFORM`, instead do a `THEN EXECUTE PROCEDURE`, and from within that trigger function expand out the json array and insert into a stream one-by-one using a cursor?
