### ISSUE TITLE
ERROR:  invalid input syntax for integer: "sw_combine_dummy"

### ISSUE THREAD

**Issue by andrew-blake** [pipelinedb/pipelinedb#1977] opened 2018-10-30 16:24 UTC
Similar error to #1972
 
```
test1=# create foreign table events_stream ( id serial, timestamp_tz timestamptz, event_id int, state int ) server pipelinedb;
CREATE FOREIGN TABLE

test1=# create view cv_sliding with (action = materialize, sw = '60 minutes', sw_column = 'timestamp_tz') as select minute(timestamp_tz) as timestamp_1m,count(*) as cnt_1m from events_stream group by 1;
CREATE VIEW

test1=# insert into events_stream (timestamp_tz, event_id, state) select now(), s.*, 0 from generate_series(1, 1000) s;
INSERT 0 1000

test1=# select * from cv_sliding;
      timestamp_1m      | cnt_1m
------------------------+--------
 2018-10-30 16:21:00+00 |   1000
(1 row)

test1=# select count(cnt_1m) from cv_sliding;
 count
-------
     1
(1 row)

test1=# select sum(cnt_1m) from cv_sliding;
 sum
------
 1000
(1 row)

test1=# select (select count(cnt_1m) from cv_sliding) as sum;
ERROR:  invalid input syntax for integer: "sw_combine_dummy"

test1=# select (select sum(cnt_1m) from cv_sliding) as sum;
ERROR:  invalid input syntax for integer: "sw_combine_dummy"
```

**Comment by derekjn** [comment] 2018-10-30 18:01
@andrew-blake confirmed, patching soon.

**Comment by derekjn** [comment] 2018-10-30 18:04
@andrew-blake as a workaround, you can rework the query into something that selects a relation, rather than an expression:

```sql
select count from (select count(count) from cv_sliding) _;
```

The issue is with aggregations on SWs evaluated as simple expressions.

**Comment by derekjn** [comment] 2018-10-30 19:10
This has been resolved. I'll reply here once a release update containing the fix has been published. Thanks so much for reporting these!

**Closed by derekjn** 2018-10-30 19:10 UTC
Labels: aggregates, bug

**Comment by derekjn** [comment] 2018-10-30 20:18
https://github.com/pipelinedb/pipelinedb/releases/tag/1.0.0rev3
