### ISSUE TITLE
test_restart_recovery hang

### ISSUE THREAD

**Issue by usmanm** [pipelinedb/pipelinedb#1517] opened 2016-05-16 22:56 UTC
https://circleci.com/gh/pipelinedb/pipelinedb/5034

**Comment by derekjn** [comment] 2016-08-02 23:06
This appears to be happening when all bg procs are starting up, and they're all waiting on a lock on `pg_database` here:

```
heap_open() at heapam.c:1,239 0x4a8158	
GetDatabaseTuple() at postinit.c:115 0x9459ed	
InitPostgres() at postinit.c:832 0x946875	
BackgroundWorkerInitializeConnection() at postmaster.c:5,509 0x76d362	
cont_bgworker_main() at cont_scheduler.c:435 0x7478e3	
StartBackgroundWorker() at bgworker.c:730 0x75982f	
do_start_bgworker() at postmaster.c:5,614 0x76d5a5	
maybe_start_bgworker() at postmaster.c:5,789 0x76d87f	
ServerLoop() at postmaster.c:1,782 0x7686b7	
PostmasterMain() at postmaster.c:1,312 0x767ac1	
main() at main.c:229 0x69ed2f	
```

I'm not sure what has the lock though because backends can't be forked at this point, and thus no queries can be run.

**Comment by usmanm** [comment] 2016-08-02 23:10
What does `pg_locks` say?

**Comment by derekjn** [comment] 2016-08-02 23:13
I can't tell because backends can't be forked at this point. This is happening in the test after the DB has been stopped and restarted, but before all bg procs are up and running.

However, the `INSERT` proc is running and waiting for the inserts to complete. I'm wondering if there is a race somewhere if the inserter starts waiting before the bg procs are online.

**Comment by usmanm** [comment] 2016-08-02 23:18
Let's wait on it till the ZMQ stuff. A bunch of this stuff is in flux right now.

**Comment by derekjn** [comment] 2016-08-02 23:18
There's an autovac proc waiting on the same lock here:

```
get_database_list() at autovacuum.c:1,848 0x756e05	
do_start_worker() at autovacuum.c:1,124 0x7560c9	
launch_worker() at autovacuum.c:1,307 0x75640d	
AutoVacLauncherMain() at autovacuum.c:775 0x7558e7	
StartAutoVacLauncher() at autovacuum.c:390 0x7551c7	
reaper() at postmaster.c:2,816 0x76a0b2	
```

It's seems strange that it's being launched from the reaper though. It's seems as if the old DB instance didn't shut down cleanly or something, although the logs look normal:

```
   / __ \(_)___  ___  / (_)___  ___  / __ \/ __ )                                                                                                                                              [6/1889]
  / /_/ / / __ \/ _ \/ / / __ \/ _ \/ / / / __  |
 / ____/ / /_/ /  __/ / / / / /  __/ /_/ / /_/ /
/_/   /_/ .___/\___/_/_/_/ /_/\___/_____/_____/
       /_/

LOG:  database system was shut down at 2016-08-02 15:53:45 PDT
LOG:  MultiXact member wraparound protections are now enabled
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
LOG:  continuous query scheduler started
LOG:  starting continuous query processes for database: "pipeline"
LOG:  ipc message broker started
LOG:  continuous query process "combiner1 [pipeline]" running with pid 25265
LOG:  continuous query process "combiner0 [pipeline]" running with pid 25266
LOG:  continuous query process "worker1 [pipeline]" running with pid 25267
LOG:  continuous query process "worker0 [pipeline]" running with pid 25268
LOG:  received fast shutdown request
LOG:  aborting any active transactions
FATAL:  terminating connection due to administrator command
LOG:  ipc message broker shutting down
LOG:  continuous query scheduler shutting down
LOG:  autovacuum launcher shutting down
LOG:  continuous query process "combiner0 [pipeline]" was killed
LOG:  continuous query process "worker0 [pipeline]" was killed
LOG:  worker process: combiner0 [pipeline] (PID 25266) exited with exit code 1
LOG:  worker process: worker0 [pipeline] (PID 25268) exited with exit code 1
LOG:  continuous query process "worker1 [pipeline]" was killed
LOG:  worker process: worker1 [pipeline] (PID 25267) exited with exit code 1
LOG:  continuous query process "combiner1 [pipeline]" was killed
LOG:  worker process: combiner1 [pipeline] (PID 25265) exited with exit code 1
LOG:  shutting down
LOG:  database system is shut down
    ____  _            ___            ____  ____
   / __ \(_)___  ___  / (_)___  ___  / __ \/ __ )
  / /_/ / / __ \/ _ \/ / / __ \/ _ \/ / / / __  |
 / ____/ / /_/ /  __/ / / / / /  __/ /_/ / /_/ /
/_/   /_/ .___/\___/_/_/_/ /_/\___/_____/_____/
       /_/

LOG:  database system was shut down at 2016-08-02 15:59:14 PDT
LOG:  MultiXact member wraparound protections are now enabled
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
LOG:  continuous query scheduler started
LOG:  ipc message broker started
LOG:  starting continuous query processes for database: "pipeline"
```

**Comment by derekjn** [comment] 2016-08-02 23:19
Ok cool i'll hold off then until the zmq diff lands. It's pretty easy to reproduce so I'm sure it will be a pretty quick fix.

**Comment by derekjn** [comment] 2016-08-02 23:36
One final datapoint: sleeping for a short time after the DB is started in the tests seems to prevent this issue from happening, which leads me to believe that there is a race between an inserter and the bgworkers. In particular, if an inserter proc is forked before the bgworkers come online, the hang seems to occur .

**Comment by derekjn** [comment] 2016-08-21 19:48
Fixed by probably a combination of the ZMQ migration and #1473.

**Closed by derekjn** 2016-08-21 19:48 UTC
Labels: bug
