### ISSUE TITLE
TRAP: FailedAssertion("!(ipcq->magic == 0xDEADBABE)", File: "queue.c", Line: 204, PID: 21801, Query: (null))

### ISSUE THREAD

**Issue by sangli00** [pipelinedb/pipelinedb#1571] opened 2016-07-07 16:42 UTC
I will start PipelineDB,ipcq process is assert.

**Comment by derekjn** [comment] 2016-07-07 16:45
@sangli00 do you have a stack trace?

**Comment by sangli00** [comment] 2016-07-07 16:48
version: PipelineDB  at revision  on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.3 20140911 (Red Hat 4.8.3-9), 64-bit
backtrace:
pipelinedb: bgworker: combiner0 [postgres]   (ExceptionalCondition+0xaf)[0x978d9f]
pipelinedb: bgworker: worker0 [postgres]   (ExceptionalCondition+0xaf)[0x978d9f]
pipelinedb: bgworker: combiner1 [postgres]   (ExceptionalCondition+0xaf)[0x978d9f]
pipelinedb: bgworker: worker1 [postgres]   (ExceptionalCondition+0xaf)[0x978d9f]
pipelinedb: bgworker: combiner0 [postgres]   (ipc_queue_unpeek_all+0x32)[0x7648fa]
pipelinedb: bgworker: worker0 [postgres]   (ipc_queue_unpeek_all+0x32)[0x7648fa]
pipelinedb: bgworker: combiner1 [postgres]   (ipc_queue_unpeek_all+0x32)[0x7648fa]
pipelinedb: bgworker: worker1 [postgres]   (ipc_queue_unpeek_all+0x32)[0x7648fa]
pipelinedb: bgworker: worker0 [postgres]   (ipc_multi_queue_unpeek_all+0x35)[0x76530e]
pipelinedb: bgworker: combiner0 [postgres]   (ContExecutorNew+0x121)[0x78b9e1]
pipelinedb: bgworker: combiner1 [postgres]   (ContExecutorNew+0x121)[0x78b9e1]
pipelinedb: bgworker: worker0 [postgres]   (ContExecutorNew+0x102)[0x78b9c2]
pipelinedb: bgworker: combiner0 [postgres]   (ContinuousQueryCombinerMain+0x1a)[0x786b3e]
pipelinedb: bgworker: worker1 [postgres]   (ipc_multi_queue_unpeek_all+0x35)[0x76530e]
pipelinedb: bgworker: combiner1 [postgres]   (ContinuousQueryCombinerMain+0x1a)[0x786b3e]
pipelinedb: bgworker: worker0 [postgres]   (ContinuousQueryWorkerMain+0x1b)[0x784599]
pipelinedb: bgworker: combiner0 [postgres]   [0x782537]
pipelinedb: bgworker: combiner1 [postgres]   [0x782537]
pipelinedb: bgworker: worker1 [postgres]   (ContExecutorNew+0x102)[0x78b9c2]
pipelinedb: bgworker: worker0 [postgres]   [0x782537]
pipelinedb: bgworker: combiner0 [postgres]   (StartBackgroundWorker+0x273)[0x79651a]
pipelinedb: bgworker: combiner1 [postgres]   (StartBackgroundWorker+0x273)[0x79651a]
pipelinedb: bgworker: worker1 [postgres]   (ContinuousQueryWorkerMain+0x1b)[0x784599]
pipelinedb: bgworker: worker0 [postgres]   (StartBackgroundWorker+0x273)[0x79651a]
pipelinedb: bgworker: combiner0 [postgres]   [0x7a9eab]
pipelinedb: bgworker: combiner1 [postgres]   [0x7a9eab]
pipelinedb: bgworker: worker1 [postgres]   [0x782537]
pipelinedb: bgworker: worker0 [postgres]   [0x7a9eab]
pipelinedb: bgworker: combiner0 [postgres]   [0x7aa182]
pipelinedb: bgworker: combiner1 [postgres]   [0x7aa182]
pipelinedb: bgworker: worker0 [postgres]   [0x7aa182]
pipelinedb: bgworker: combiner0 [postgres]   [0x7a4df1]
pipelinedb: bgworker: worker1 [postgres]   (StartBackgroundWorker+0x273)[0x79651a]
pipelinedb: bgworker: combiner1 [postgres]   [0x7a4df1]
pipelinedb: bgworker: worker0 [postgres]   [0x7a4df1]
pipelinedb: bgworker: combiner0 [postgres]   (PostmasterMain+0x10fb)[0x7a4215]
pipelinedb: bgworker: combiner1 [postgres]   (PostmasterMain+0x10fb)[0x7a4215]
pipelinedb: bgworker: worker1 [postgres]   [0x7a9eab]
pipelinedb: bgworker: combiner0 [postgres]   [0x6cceca]
pipelinedb: bgworker: worker0 [postgres]   (PostmasterMain+0x10fb)[0x7a4215]
pipelinedb: bgworker: combiner1 [postgres]   [0x6cceca]
/lib64/libc.so.6(__libc_start_main+0xf5)[0x7f0e46439b15]
/lib64/libc.so.6(__libc_start_main+0xf5)[0x7f0e46439b15]
pipelinedb: bgworker: worker1 [postgres]   [0x7aa182]
pipelinedb: bgworker: worker0 [postgres]   [0x6cceca]
pipelinedb: bgworker: combiner0 [postgres]   [0x46f279]
pipelinedb: bgworker: combiner1 [postgres]   [0x46f279]
/lib64/libc.so.6(__libc_start_main+0xf5)[0x7f0e46439b15]
pipelinedb: bgworker: worker1 [postgres]   [0x7a4df1]
pipelinedb: bgworker: worker0 [postgres]   [0x46f279]
pipelinedb: bgworker: worker1 [postgres]   (PostmasterMain+0x10fb)[0x7a4215]
pipelinedb: bgworker: worker1 [postgres]   [0x6cceca]
/lib64/libc.so.6(__libc_start_main+0xf5)[0x7f0e46439b15]
pipelinedb: bgworker: worker1 [postgres]   [0x46f279]
LOG:  worker process: apms (PID 21790) exited with exit code 1
LOG:  worker process: combiner0 [postgres] (PID 21798) was terminated by signal 6: Aborted
DETAIL:  Failed process was running: combiner0 [postgres]
LOG:  terminating any other active server processes
WARNING:  terminating connection because of crash of another server process
DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another

**Comment by sangli00** [comment] 2016-07-07 16:49
this is full  stack trace

**Comment by derekjn** [comment] 2016-07-07 16:56
Is this your own build? It appears that this isn't a nightly or official release.

**Comment by sangli00** [comment] 2016-07-07 17:10
yes, I build  ,source from github.  version 0.9.3 master.

**Comment by derekjn** [comment] 2016-07-07 17:10
Thanks, can you give us steps to reproduce this?

**Comment by sangli00** [comment] 2016-07-07 17:18
I execute command  /usr/local/pipelinedb/bin/pipeline-ctl -D db1/ -l logfile start -m fast

**Comment by derekjn** [comment] 2016-07-13 16:40
Closing this as I've been unable to reproduce and it's not clear what changes have been made to the build in question.

**Closed by derekjn** 2016-07-13 16:40 UTC
